### ISSUE TITLE
Pytorch Lightning as a back-end

### ISSUE THREAD

**Issue by williamFalcon** [feedly/transfer-nlp#72]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Hi! check out Pytorch Lightning as an option for your backend! We're looking for awesome project implemented in Lightning.

https://github.com/williamFalcon/pytorch-lightning
**Additional context**

**Comment by petermartigny** [comment]
Hi @williamFalcon !
Pytorch Lightning seems great, I will have a look at it.
The transfer learning part of Transfer NLP aims at providing flexible trainers, so we could imagine having both [ignite](https://github.com/pytorch/ignite) and [lightning](https://github.com/williamFalcon/pytorch-lightning) versions of the trainers to deal with the differences you mention in your [medium post](https://towardsdatascience.com/pytorch-lightning-vs-pytorch-ignite-vs-fast-ai-61dc7480ad8a)

**Comment by petermartigny** [comment]
No follow up, closing the issue

**Comment by williamFalcon** [comment]
sorry, forgot about this. 

here’s the example as requested 

https://towardsdatascience.com/lit-bert-nlp-transfer-learning-in-3-steps-272a866570db
